services:
  api:
    container_name: api.dw.com
    build:
      context: personal_api/
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    expose:
      - "8000"
    env_file:
      - personal_api/.env
    environment:
      - GUNICORN_WORKERS=4
    depends_on:
      db:
        condition: service_healthy
    networks:
      1vision:
        ipv4_address: 172.19.1.10
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs').read()"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    container_name: dw.com
    build:
      context: personal_site/
      dockerfile: Dockerfile-dev
    restart: always
    expose:
      - "5173"
    ports:
      - "80:5173"
    environment:
      NODE_ENV: production
      CHOKIDAR_USEPOLLING: true
    volumes:
      - "./personal_site:/app"
      - "/app/node_modules"
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      1vision:
        ipv4_address: 172.19.1.20
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: axiosmedia/postgres-pgvector:15.8-0.7.3
    container_name: pgsql.dw.com
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - "pg_portfolio:/var/lib/postgresql/data"
      - "./db/initdb:/docker-entrypoint-initdb.d"
    networks:
      1vision:
        ipv4_address: 172.19.1.30
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  frontend:
    driver: local
  pg_portfolio:
    driver: local

networks:
  1vision:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.19.1.0/26"
#          ip_range: 172.19.1.0/26
#          gateway: 172.19.1.1
